### ISSUE TITLE
Update health states without user interaction

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#32]
## User story
1. As a user
2. I want / need a health state of a specific container
3. So that I can quickly see the container's current state on its detail page

## Acceptance criteria
- [ ] State should change accordingly to database as fast as possible
- [ ] Display the state as both colour and text
- [ ] Text is always easily readable
- [ ] The health indicator is based on the container states
- [ ] Green on successfully terminated
- [ ] Red on terminated with error
- [ ] Green on running
- [ ] Yellow on waiting
- [ ] State information is loaded from database

## Additional Information
- The implementation is done as reusable, configurable component
- Please prepare something to showcase the state change
- Event-driven update would be nice, periodic updates are fine for now

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by njochens** [comment]
Found out that `React Components` have functions `componentDidMount()` and `componentWillUnmount()` that allow for a periodical updates by overwriting them in the following way:

`componentDidMount() {
  this.interval = setInterval(() => this.setState({ time: Date.now() }), 1000);
}
componentWillUnmount() {
  clearInterval(this.interval);
}`

This should update the component every second and therefore fetch the new information from the database. Problem is that we are currently using `JSX:Element` that might need to be changed to React `Component`.

Otherwise no progress.

**Comment by jandegen** [comment]
No tests required
